version: '3'
services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: use-case-gpt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    image: use-case-gpt-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db/use_case_gpt
    ports:
      - "8000:8000"
